import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>You shouldnt be here</h1>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://www.google.com"
					target="_blank"
					rel="noopener noreferrer"
				>
					<span className={styles.logo}>
						{" "}
						Powered by{" your momma"}
					</span>
				</a>
			</footer>
		</div>
	)
}
